version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: eventsdb
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgres_network:
    name: postgres_network
    driver: bridge